services:
  - type: web
    name: be-todo
    runtime: docker
    dockerfilePath: ./backend/Dockerfile

  - type: web
    name: fe-todo
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
  - type: pserv
    name: todo-db

  - type: web
    name: be-todo
    runtime: docker
    dockerfilePath: ./backend/Dockerfile

  - type: web
    name: fe-todo
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile