services:
  - type: pserv
    name: todo-db
    ipAllowList: []

  - type: web
    name: be-todo
    dockerfilePath: ./backend/Dockerfile

  - type: web
    name: fe-todo
    dockerfilePath: ./frontend/Dockerfile